### ISSUE TITLE
Recent commit calling `posix_getpwuid()` breaks on Windows

### ISSUE THREAD

**Issue by grasmash** [typhonius/acquia-php-sdk-v2#101]
This commit https://github.com/typhonius/acquia-php-sdk-v2/commit/a301ebd5ef18d7cd2f314dfca1fda9e660bb6155 has broken windows compatibility by calling `posix_getpwuid()`, which apparently does not exist in PHP on Windows.

**Comment by grasmash** [comment]
See https://www.php.net/manual/en/function.posix-getpwuid.php:

> To properly get the running user, test if function_exists('posix_getpwuid') and if not, assume you're running on Windows and call getenv('USERNAME').

**Comment by typhonius** [comment]
That'll teach me what blindly following [StackOverflow posts](https://stackoverflow.com/a/30926828) will do. I've decided for now, the easiest way of getting the home directory on different platforms is to use a tiny existing library that does the job for me.
