### ISSUE TITLE
1.0.3 release?

### ISSUE THREAD

**Issue by lcatlett** [typhonius/acquia-php-sdk-v2#16]
Are there plans for a 1.0.3 release in the forseeable future? BLT previously required this package at ^1.0.2 and we would benefit from bugfixes that have been pushed to the master branch but are not yet available in a stable release on packagist.

**Comment by typhonius** [comment]
Don't see why not! I've pushed a 1.0.3 release now as the code has been fairly static without complaints and the diff between this and 1.0.2 is very minor.
