### ISSUE TITLE
DatabaseBackups::download memory usage

### ISSUE THREAD

**Issue by danepowell** [typhonius/acquia-php-sdk-v2#185]
DatabaseBackups::download() returns a stream resource, therefore I would expect it to not load the entire db backup into memory, but rather return a stream that can be written to disk. However, in practice memory usage appears to match the size of a given db backup. This obviously causes a problem if your db backup is larger than your PHP memory limit.

```
$database_backups = new DatabaseBackups($acquia_cloud_client);
$database_backups->download($environment->uuid, $database->name, $backup_response->id); // huge memory usage here
```

**Comment by typhonius** [comment]
I thought this sounded familiar and I think it's something that I ran into when we first created this method.

From memory, the only way to get around this was to tell curl where to stream this to, and to do that you need to know the backup location etc. I decided at the time that this was out of scope for the SDK as it should be limited to making the request and giving the resource back.

That said, I _think_ what I did to get round it was expose curl options which you ***can*** use to give a [download location](https://docs.guzzlephp.org/en/stable/request-options.html#sink) to e.g. https://github.com/typhonius/acquia_cli/blob/master/src/Commands/DbBackupCommand.php#L237-L241

Could you do me a favour and try adding those curl opts to your call?

**Comment by danepowell** [comment]
Thanks for the reference. I tried adding those opts but the problem persists:
```
$acquia_cloud_client->addOption('sink', $local_filepath);
$acquia_cloud_client->addOption('curl.options', ['CURLOPT_RETURNTRANSFER' => true, 'CURLOPT_FILE' => $local_filepath]);
$database_backups = new DatabaseBackups($acquia_cloud_client);
$database_backups->download($environment->uuid, $database->name, $backup_response->id);
$output_callback('out', 'peak memory usage: ' . memory_get_peak_usage()); // something awful
```

I've confirmed that those curl opts _do_ have the effect of streaming the file to disk at `$local_filepath`, so I think the problem isn't there. It looks like the problem is actually later: https://github.com/typhonius/acquia-php-sdk-v2/blob/67afe42be076547cb90a5bcda13c3e146a408f09/src/Connector/Client.php#L144

When `processResponse()` tries to decode the response, I suspect it forces the stream to load into memory. I don't think this is something a downstream library can work around.

**Comment by typhonius** [comment]
> When `processResponse()` tries to decode the response, I suspect it forces the stream to load into memory. I don't think this is something a downstream library can work around.

Great catch and something that it shouldn't do. I'd been thinking about splitting out methods for processing streams vs non-streams (not for this reason but I had a good reason) and I think this is going to be a good catalyst to do so now.

From memory, the reason `json_last_error` is in there is to handle streamed responses which is honestly a bit lazy.

**Comment by typhonius** [comment]
Oh I remember, it was because one of the PHP linters/checkers kept having a sad about me passing back `mixed|StreamInterface` from request. I figured it was mostly aesthetic to change since this is all pretty deep in the guts of the library but it's probably reasonably simple to do. Substitute the call to `request()` in any of the endpoints returning a stream for a new `stream()` method and deal appropriately from there.

**Comment by danepowell** [comment]
@typhonius that makes sense, thanks for diving in. Is this on your roadmap to fix, or do you need me to help?

**Comment by typhonius** [comment]
Could you try #191 out for size? I had a go and on a 250MB DB peaked memory at 6MB. That said, I'd rather someone tested who'd touched PHP in the last 6months :P

**Comment by danepowell** [comment]
Nevermind, I'm an idiot. If I tell it to only accept JSON, go figure that I get JSON back instead of the actual resource.
