### ISSUE TITLE
Unable to delete a database

### ISSUE THREAD

**Issue by q0rban** [typhonius/acquia-php-sdk-v2#19]
When attempting to delete a database:

``` 
[error]  The method "post" is not available for the resource "api/applications/[redacted]/databases/[db-name]".
```

I noticed [in the docs](http://cloudapi-docs.acquia.com/#operation/postApplicationDatabaseDelete) that it expects a `DEL` request, so I changed it to that, but I still get an error. Maybe it's a bug in their API?

**Comment by typhonius** [comment]
@seanhamlin I know that you've been pretty responsive to bugs we've found in the API. Are you able to investigate this one please?

**Comment by seanhamlin** [comment]
Hey @q0rban, I assume you mean you changed the HTTP method to `DELETE` (not `DEL`), and I also assume you have the permission needed to drop a db ([see the docs](https://docs.acquia.com/acquia-cloud/access/teams/permissions/#cloud-permslist-db))?

**Comment by jayakrishnanj** [comment]
API is working fine. Delete Permission is required to delete the DB, however this issue is due to the HTTP method 'delete'. Raised PR to fix this issue. Document Link: https://cloudapi-docs.acquia.com/#/Applications/postApplicationDatabaseDelete

**Comment by q0rban** [comment]
> Hey @q0rban, I assume you mean you changed the HTTP method to DELETE (not DEL), and I also assume you have the permission needed to drop a db (see the docs)?

Ah, that was probably my problem. I should have changed it to `delete` not `del`. 🤦‍♂  Thanks for working on this!
