### ISSUE TITLE
Push / maintainer access

### ISSUE THREAD

**Issue by danepowell** [typhonius/acquia-php-sdk-v2#194]
Hey @typhonius , you mentioned that you weren't working with this project (or indeed, PHP) much lately. Would you consider giving push access to @grasmash and myself to help with maintenance? We'd treat it like any other Acquia project and make sure that PRs go through a thorough review process before merging, and follow your lead on any other best practices.

**Comment by typhonius** [comment]
Yes, I'd love the help thank you! Will make you both maintainers now.
