### ISSUE TITLE
Add account method

### ISSUE THREAD

**Issue by danepowell** [typhonius/acquia-php-sdk-v2#20]
It would be nice if there was a way to call the `account` endpoint. It doesn't seem like this is possible now. This could be a dedicated account method, or a method that lets you call arbitrary endpoints that might not yet be supported by this package.

My use case isn't really to get account info, but to check that authentication was successful. I've been told that calling `account` is significantly less expensive than calling other methods like `applications`.

**Comment by typhonius** [comment]
Thanks @danepowell this is easy enough to add so I'll do so now. One thing I have already noticed though is that the docs for this (https://cloudapi-docs.acquia.com/#/Account/getAccount) do not include the 'created_at' element that the API responds with. Could you work internally to get that added to the docs so our tests work based on what the docs provide?

**Comment by typhonius** [comment]
I wonder if the 'system status' endpoint is even less expensive too.

**Comment by danepowell** [comment]
Thanks I'm creating an internal ticket and will cc you

**Comment by danepowell** [comment]
@typhonius you should be able to see the corrected documentation now: https://cloudapi-docs.acquia.com/#/Account/getAccount
