### ISSUE TITLE
Fatal error: Uncaught Error: Wrong parameters for Exception

### ISSUE THREAD

**Issue by richardbporter** [typhonius/acquia-php-sdk-v2#26]
I'm getting the following error when trying to catch an exception thrown as a the result of a 400. In this case, attempting to create a database that already exists.

```
try {
  $cloud->databaseCreate($application->uuid, $db);
} catch (\Exception $e) {
    // Log something.
}
```

```
Client error: `POST https://cloud.acquia.com/api/applications/xxx/databases` resulted in a `400 Bad Request` response:
{
    "error": "validation_failed",
    "message": {
        "name": "A database with that name already exists. Please c (truncated...)
```

Is there a way to hide that JSON output?

```
Fatal error: Uncaught Error: Wrong parameters for Exception([string $message [, long $code [, Throwable $previous = NULL]]]) in vendor/typhonius/acquia-php-sdk-v2/src/CloudApi/Connector.php on line 119
```

Is this possible or am I supposed to code around these? Thanks!

**Comment by richardbporter** [comment]
> Is there a way to hide that JSON output?

Looks like no: https://github.com/typhonius/acquia-php-sdk-v2/blob/master/src/CloudApi/Connector.php#L88

It looks like Connector::processResponse is choking on an `$object->message` that it expects to be a string? In this case, I'm seeing it as an object with a name property, i.e. `$object->message->name`. Maybe an update to the API changed this?

**Comment by typhonius** [comment]
@grasmash this looks like an Acquia question. Would you have a view on whether this is an API change?

**Comment by typhonius** [comment]
This might be fixed by #39 - can you check it out please?

**Comment by typhonius** [comment]
I'm closing this now as after a considerable amount of change to both this library and `typhonius/acquia_cli` I'm getting nice error messages when I run the following command:

```
acquiacli db:create sitename dbName
```

I think this is provided by Robo automatically, although I'm not 100% on that.

**Comment by richardbporter** [comment]
Thanks and sorry for not getting back to this sooner.
