### ISSUE TITLE
Add domainStatus method to Client

### ISSUE THREAD

**Issue by richardbporter** [typhonius/acquia-php-sdk-v2#28]
The domain status endpoint has some additional information that could be useful like dns_resolves and acquia_hosted flags. It would be nice to have another method to process these responses.

https://cloudapi-docs.acquia.com/#/Environments/getEnvironmentsDomainStatus

**Comment by typhonius** [comment]
This has been added in the 2.0 branch.

```
use AcquiaCloudApi\Endpoints\Domains;

$domain = new Domains($client);
$status = $domain->status('EnvUUID', 'domain.name');
```

**Comment by richardbporter** [comment]
Thanks!
