### ISSUE TITLE
Switch authentication from HMAC to OAuth 2.0

### ISSUE THREAD

**Issue by eporama** [typhonius/acquia-php-sdk-v2#30]
The HMAC authentication process is deprecated from Cloud API v2. 

All of the documentation points to using an OAuth 2.0 token process.

**Comment by eporama** [comment]
https://docs.acquia.com/acquia-cloud/develop/api/auth/

the sample script appears to use https://github.com/thephpleague/oauth2-client

**Comment by typhonius** [comment]
Thanks for this - I've created 1.1.0 for this.
