### ISSUE TITLE
PHP 7.4 EOL

### ISSUE THREAD

**Issue by danepowell** [typhonius/acquia-php-sdk-v2#321]
PHP 7.4 has been EOL for a while now, we should consider dropping support for it including removing it from composer.json, removing it from test workflows, and removing it from required status checks.

**Comment by typhonius** [comment]
Thanks for this, and I see in #322 you've added in 8.2. I have no issues with removing 7.4 (and associated checks in GH Actions). Technically would this require a new major version as it's a potentially breaking change for some users? I also don't want to be too dogmatic about it as that also sounds like a pain/less pragmatic so maybe a new minor version?

**Comment by danepowell** [comment]
It's not really breaking since Composer will be smart enough not to upgrade folks still on PHP 7.4. It's just end of the line for them.

The only reason I see for a major release would be to continue supporting PHP 7.4 in some capacity on the old branch.

**Comment by danepowell** [comment]
I cut a new final release before the PHP 7.4 EOL so that any straggling PHP 7 users can at least have the latest and greatest changes before it dies.
