### ISSUE TITLE
Responses are lacking information

### ISSUE THREAD

**Issue by gCardinal** [typhonius/acquia-php-sdk-v2#33]
When using the API directly, each endpoint will return a lot of information on the current request's result, including other endpoints should we require more information. This is useful for things like waiting for a database backup to be complete.

As it is, this library a simple message, without any additional info the API would normally provide.

Is this an intended limitation? If so, how would one wait for a given task to finish before moving on to something else?

**Comment by typhonius** [comment]
Hi there, @gCardinal, definitely not intentional if there's a way the API can provide this information. Could you help me further with the database backup example about what the API sends back which would be useful for you?

In the Acquia Cli library, I added a [waitForTask method](https://github.com/typhonius/acquia_cli/blob/master/src/Commands/AcquiaCommand.php#L172-L258) which looks up the tasks by task ID and waits until it's complete. The reason I did this was because previously the API didn't send back something we could directly query. If that's changed, it'd be great to add into this library.

**Comment by typhonius** [comment]
Would you be essentially looking for the [OperationResponse](https://github.com/typhonius/acquia-php-sdk-v2/blob/1.1/src/Response/OperationResponse.php) class to have additional properties for '_links' based on [this](https://cloudapi-docs.acquia.com/#/Environments/postEnvironmentsDatabaseBackups)

**Comment by typhonius** [comment]
Looking into this further, I think we can use the Notification endpoint to retrieve structured data for responses which is going to be way better than the existing method. @eporama started on that work here: https://github.com/typhonius/acquia-php-sdk-v2/pull/24

**Comment by q0rban** [comment]
I didn't know there was a waitForTask method, that's helpful to know. Of course, the issue described here is that one must know _which_ task to wait for. On a busy project, you can't reliably ask the API "which task is the most recent", and assume that is the one the correct task.

That was my reasoning in creating the workaround for the API in the [Robo Acquia Cloud API task runner](https://github.com/Lullabot/robo-acquia#waiting-for-task-completion).

**Comment by gCardinal** [comment]
@q0rban: Most endpoints now will return a `_links` object with a list of endpoints you might want to call, including one `notification` endpoint that is essentially the endpoint to call to determine the status of the job you just sent.

@typhonius: #35 would indeed solve this issue :). It might be interesting later on to have the ability to do tasks "synchronously", but now I'm just being spoiled.

**Comment by typhonius** [comment]
Agree on that point and waitForTask was a huge workaround at a time when the Notifications endpoint didn't exist. Great it's now in there as it will provide a more stable mechanism of identifying the right task to wait for. Once Notifications are in here, I'd like to update Acquia Cli to wait better.

@gCardinal Acquia Cli does this to an extent by waiting for tasks to complete and by using a locking mechanism to ensure tasks are fired off in order. Thanks for the check on #35 I'll get that merged in to this branch and the newer 2.0 branch.
