### ISSUE TITLE
Access Token is expiring after 300 seconds

### ISSUE THREAD

**Issue by lnunesbr** [typhonius/acquia-php-sdk-v2#48]
**Is your feature request related to a problem? Please describe.**
Token is expiring after 300 seconds. This is expected as per acquia docs: https://docs.acquia.com/acquia-cloud/develop/api/auth/

> The API token will expire 300 seconds (or 5 minutes) after you generate it and must be regenerated before then.

This is failing with exception message: _**The access token has expired.**_

**Describe the solution you'd like**
Connector should be able to auto regenerate the auth token after that time is past.

**Describe alternatives you've considered**

**Additional context**

**Comment by typhonius** [comment]
Thanks for this. Is there a specific command or API call you’re using so I can try and replicate?

**Comment by generalredneck** [comment]
This happens with me when using acquia_cli and running something like db:backup or db:copy:all where the database is big enough it takes longer than 5 minutes.

**Comment by generalredneck** [comment]
So I see how the CLI client is different because you actually programmed a "waitForTask" function over there... so I think the solution here would be to recreate the client everytime you run an api command like is done in acquiacli here: https://github.com/typhonius/acquia_cli/blob/30a36b3d3bcea4e960384590590314c9f56c3cd7/src/Commands/AcquiaCommand.php#L61-L65

**Comment by typhonius** [comment]
Yeah I think that makes sense. If we add in a timer that creates a new client once we’re approaching the token mac age I think that’d work pretty well. Thanks for your investigation into this.

**Comment by gCardinal** [comment]
I am also hitting this issue sometimes. I'm using this library to move code, files and databases from environment to environment and sometimes operations on Acquia's side will take long enough that my token will simply expire.

[See this screenshot here (with "custom" messaging by me)](https://i.imgur.com/Nmsouje.png).

Digging into the code, it seems like the Connector class should be able to automatically recreate a token when needed, am I wrong. That would really be useful.

**Comment by typhonius** [comment]
I’ve checked the responses from Acquia and it doesn’t look like they implement a refresh token unfortunately. We can however determine when it’s expired so that could be something to use.

**Comment by gCardinal** [comment]
I know (which is weird to be honest), but recreating the token also works, though, not as reliably as I'd like, but that might be my implementation.

The Connector class could recreate (not refresh) the token before it expires, wouldn't it?

**Comment by typhonius** [comment]
#49 seems to work for me. Could you please check to see if it works for your purposes too?
