### ISSUE TITLE
Why is codesniffer a require and not a dev require?

### ISSUE THREAD

**Issue by generalredneck** [typhonius/acquia-php-sdk-v2#61]
I've been trying to use [cgr](https://github.com/consolidation/cgr) to install acquia_cli, but my version of phpcbf and phpcs keeps getting clobbered by the version this library is using. I don't think Acquia requires you to use codesniffer to use it, so I would suggest moving it if possible.

**Comment by typhonius** [comment]
Thanks for this - totally an oversight as it should only be a dev dependency!
