### ISSUE TITLE
Add support for deleting database backups.

### ISSUE THREAD

**Issue by pcate-fls** [typhonius/acquia-php-sdk-v2#64]
When deploying new code to production and staging I first create a DB backup through the API (thanks for this library which makes doing that much easier!) Unfortunately over time those backups pile up and are no longer needed.

It would be great if the library supported deleting database backups. There is a API endpoint available for this: https://cloudapi-docs.acquia.com/#/Environments/deleteEnvironmentsDatabaseBackup

Right now I have to manually delete backups, but if this feature was added it could be automated as part of my deployment process..

**Comment by typhonius** [comment]
Great idea, thanks for submitting this request. I've added this functionality into the library and it'll be available with the next tag download. I'll also create a parallel request over in Acquia Cli.

**Comment by typhonius** [comment]
Linking https://github.com/typhonius/acquia_cli/pull/80
