### ISSUE TITLE
Wrong SslCertificates enable/disable endpoint

### ISSUE THREAD

**Issue by tdenolle** [typhonius/acquia-php-sdk-v2#67]
**Describe the bug**
SslCertificates endpoint for enabling/disabling certificate is not correct.
Acquia Cloud API Endpoint has to be /environments/${uuid}/ssl/certificates/... 

**To Reproduce**
When calling enable or disable function, following message is displayed : 
> [error]  The path "api/environments/XXX/ssl/certificate/1234/actions/activate" does not match any known resources.

**Expected behavior**
Certificate should be activated/desactivated witthout error.

**Comment by typhonius** [comment]
Fixed in #68
