### ISSUE TITLE
Make request does not check if token is expired in v1.1.1

### ISSUE THREAD

**Issue by josephdpurcell** [typhonius/acquia-php-sdk-v2#71]
**Describe the bug**
The makeRequest() method on src/CloudApi/Connector.php does not check if the access token has expired.

**To Reproduce**
1. In a long running process, setup an access token
2. Call makeRequest()
3. Wait 5 minutes
4. Call makeRequest() again
5. Notice an exception is thrown with a 403 Forbidden response from the API:

```
{
    "error": "unauthorized",
    "message": "The access token has expired."
}
```

**Expected behavior**
When a request is made the second time, a check is made if the token is expired. If it is expired, get a new one.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Code version/tag: 1.1.1

**Additional context**
https://github.com/typhonius/acquia-php-sdk-v2/issues/48 seems related.

This issue is fixed in the latest, see: https://github.com/typhonius/acquia-php-sdk-v2/blob/master/src/Connector/Connector.php#L59

This issue will be expired currently by anyone using https://github.com/lcatlett/blt-drush-alias/blob/master/composer.json#L15 because it locks this library to v1.

**Comment by josephdpurcell** [comment]
If you need to solve this issue and you can't wait for v1 to be hotfixed, and you can't use v2, you can solve this with the attached patch:

[71-check-access-token.patch.txt](https://github.com/typhonius/acquia-php-sdk-v2/files/4713239/71-check-access-token.patch.txt)

And adding this to your composer.json:

```
    "patches": {
            "typhonius/acquia-php-sdk-v2": {
                "Check access token #71": "patches/71-check-access-token.patch.txt"
            }
```

**Comment by typhonius** [comment]
Thanks for this and the PR. As it's nowhere near breaking an API and constitutes an issue that I'm sure others will face I've rolled it in and will tag `1.1.2` on this branch.

**Comment by josephdpurcell** [comment]
This is great!

Now, to take advantage of this if you're on 1x of this repo is to do:

```
composer update typhonius/acquia-php-sdk-v2
```

Thank you for a swift update!
