### ISSUE TITLE
Set user agent for requests

### ISSUE THREAD

**Issue by danepowell** [typhonius/acquia-php-sdk-v2#73]
**Is your feature request related to a problem? Please describe.**
Currently, Cloud API requests from Acquia PHP SDK have a generic, default user agent string provided by Guzzle, i.e. `GuzzleHttp/6.5.4 curl/7.68.0 PHP/7.4.3`. This makes it difficult to monitor and debug failing requests from the server side, and trace them back to projects using Acquia PHP SDK.

**Describe the solution you'd like**
A unique identifier prepended to the user agent string, such as `acquia-php-sdk-v2`, and/or the ability for downstream projects to set their own user agent string.

**Describe alternatives you've considered**
I can't think of any. The current string isn't unique enough on its own to be useful, and there's no way I can see to override it from a downstream/consuming project.

If you want a more extensive solution, though, you could expose all of the headers to modification by consuming projects, not just the user-agent.

**Additional context**
I'm happy to help with a PR if you can let me know what approach you prefer. Thanks!

**Comment by typhonius** [comment]
That's a pretty cool idea - I'm a big fan of open data so will Acquia be able to publish some analytics/stats about user agents hitting the API?

It looks like the easiest solution here is to alter how we instantiate the Guzzle client. I'll have a think about the right user agent although probably some combination of the library name plus the version in use as this may assist in debugging customers with different versions to support staff.

I haven't dug into it to check, but dependent libraries might be able to use the `addOption` method to add their own user agent. This creates an array that gets used when creating the Guzzle object. I use it in Acquia Cli over here to pass specific parameters required by Guzzle for downloading files: https://github.com/typhonius/acquia_cli/blob/b043a3204cc9b8a1557764ede5f2bfe2328d394a/src/Commands/DbBackupCommand.php#L238-L244

**Comment by typhonius** [comment]
From http://docs.guzzlephp.org/en/stable/request-options.html#headers dependent libraries would probably do something like:

`$client->addOption(['headers' => ['User-Agent' => 'acquiacli/$version']]);
`

**Comment by typhonius** [comment]
I've just added a PR for this one too. Would be great if I could get your eyes on #74 in case it would cause any unforeseen issues.
