### ISSUE TITLE
Using x-www-form-urlencoded is untyped and causes issues with api backend validation

### ISSUE THREAD

**Issue by eporama** [typhonius/acquia-php-sdk-v2#81]
**Describe the bug**
As an example, the `environment->update()` method should take values like `['memory_limit' => 192]`, however, the API returns: 

```
PHP Fatal error:  Uncaught AcquiaCloudApi\Exception\ApiErrorException: [0]: 192 is not a valid memory limit. It should be an integer.
```

This is because `x-www-form-urlencoded` is not typed and everything comes through as a string. I am trying to track down any documentation on this on Acquia's side, but confirmed with the API team last year about boolean values.

**To Reproduce**
```
$environment = new Environments($client);
$environmentUuid = '<REDACTED>';
$config = [
  'memory_limit' => 152,
];

$environment->update($environmentUuid, $config);
```

**Expected behavior**
I expect that it succeeds.

**Comment by eporama** [comment]
```
diff --git a/src/Endpoints/Environments.php b/src/Endpoints/Environments.php
index cdd9c5b..541f130 100644
--- a/src/Endpoints/Environments.php
+++ b/src/Endpoints/Environments.php
@@ -77,7 +77,8 @@ class Environments extends CloudApiBase implements CloudApiInterface
     {

         $options = [
-            'form_params' => $config,
+            'body' => json_encode($config),
+            'headers' => 'Content-Type: application/json',
         ];

         return new OperationResponse(
```

This diff actually did work for the `update()` method on environments… so it's a valid approach? I think setting the `Content-Type: application/json` more globally would be fine as well; especially for PUT/POST methods. But I assume it works for GET as well.

**Comment by eporama** [comment]
actually, this is even easier:

```
diff --git a/src/Endpoints/Environments.php b/src/Endpoints/Environments.php
index cdd9c5b..1f225ad 100644
--- a/src/Endpoints/Environments.php
+++ b/src/Endpoints/Environments.php
@@ -77,7 +77,7 @@ class Environments extends CloudApiBase implements CloudApiInterface
     {

         $options = [
-            'form_params' => $config,
+            'json' => $config,
         ];

         return new OperationResponse(
```

Turns out that the `json` option does both the encoding and the content-type header!

**Comment by typhonius** [comment]
I’ve just checked the documentation on Acquia’s side and it looks like there’s a case for form-urlencoded parameters (https://cloudapi-docs.acquia.com/#/Environments/putEnvironment).

I agree that the associated PR to change everything to JSON encoding would be preferable so I’ll continue testing to incorporate #82 but it might also be useful to adjust the docs page too.

**Comment by eporama** [comment]
I agree that the documentation still allows `x-www-form-urlencoded`… But in talking with the maintainers, they're preparing to make it deprecated because of this issue and they consider it to be the incorrect approach :-( So now I simply need to get them to update the docs via the spec.
